environment:
    write_timeout: 10s
    read_timeout: 10s
    mongo_host: "mongodb+srv://%s:%s@cluster0-l6ojz.mongodb.net/%s?retryWrites=true&w=majority"
    mongo_user: telar_user
    mongo_pwd_path: "/var/openfaas/secrets/mongo-pwd"
    mongo_database: test
    public_key_path: "/var/openfaas/secrets/key.pub"
    recaptcha_key_path: "/var/openfaas/secrets/recaptcha-key"
    recaptcha_site_key: "6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW"
    private_key_path: "/var/openfaas/secrets/key"
    header_cookie_name: "he"
    payload_cookie_name: "pa"
    signature_cookie_name: "si"
    org_name: "Red Gold"
    org_avatar: "https://avatars3.githubusercontent.com/u/43268620"
    db_type: mongo
    app_name: "Telar Social"
    smtp_email: "smtp.gmail.com"
    ref_email: "polling.social@gmail.com"
    ref_email_pass_path: "/var/openfaas/secrets/ref-email-pass"
    phone_auth_token_path: "/var/openfaas/secrets/phone-auth-token"
    phone_auth_id_path: "/var/openfaas/secrets/phone-auth-id"
    phone_source_number: "0123456"
    