environment:
  app_name: Telar Social
  db_type: mongo
  header_cookie_name: he
  mongo_database: test
  mongo_host: mongodb+srv://telar:%s@cluster0.l6ojz.mongodb.net/test?retryWrites=true&w=majority
  mongo_pwd_path: /var/openfaas/secrets/mongo-pwd
  org_avatar: https://avatars3.githubusercontent.com/u/43268620
  org_name: Red Gold
  payload_cookie_name: pa
  phone_auth_id_path: /var/openfaas/secrets/phone-auth-id
  phone_auth_token_path: /var/openfaas/secrets/phone-auth-token
  phone_source_number: "0123456"
  private_key_path: /var/openfaas/secrets/key
  public_key_path: /var/openfaas/secrets/key.pub
  read_timeout: 10s
  recaptcha_key_path: /var/openfaas/secrets/recaptcha-key
  recaptcha_site_key: 6LfXPboUAAAAAIQmwp8HVll7n7ZUpwNW1JL5RcoW
  ref_email: polling.social@gmail.com
  ref_email_pass_path: /var/openfaas/secrets/ref-email-pass
  signature_cookie_name: si
  smtp_email: smtp.gmail.com
  write_timeout: 10s
